select
    id as product_id,  
    nan,  
    version,  
    product_name,  
    attributes__tags__discounted__label,
    _embedded__category_path  as category_path,
    has_variants,
    has_diverse_variant_prices  ,
    should_details_link_be_masked , 
    free_shipping  ,
    _links__detail__href  as link,
    _dlt_load_id  ,
    _dlt_id  ,
    attributes__tags__organic__label  ,
    brand__name  as brand,
    attributes__tags__has_loyalty_bonus__label,  
    attributes__tags__lowestprice__label,  
    loyalty_bonus__bonus_type,  
    loyalty_bonus__bonus_value , 
    attributes__tags__regional__label,  
    attributes__tags__lactosefree__label,  
    attributes__tags__vegan__label,  
    attributes__tags__vegetarian__label,  
    reusable_container,  
    bulky_goods_points  
from {{ source('rewe_products', 'rewe_products') }}